---
name: 'Build Image'
on:
  schedule:
    - cron: '22 4 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: 'OCI'
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    with:
      image_name: spring-petclinic
